USE TartangaPrimeVideo;

/*CREATE TABLE TRABAJADOR 
(ID_T VARCHAR(20) PRIMARY KEY,
CONTRASENIA VARCHAR(20),
NOMBRE VARCHAR(20),
SUELDO FLOAT,
TIPO ENUM("ADMIN", "TRABAJADOR") NOT NULL);

CREATE TABLE GENERO
(ID_G VARCHAR(20) PRIMARY KEY,
CATEGORIA VARCHAR(20));

CREATE TABLE PELICULA
(ID_P VARCHAR(20) PRIMARY KEY,
NOMBRE VARCHAR(20),
PRECIO FLOAT,
DURACION INT,
CALIFICACION FLOAT,
ID_G VARCHAR(20),
ID_T VARCHAR(20),
FOREIGN KEY (ID_G) REFERENCES GENERO (ID_G),
FOREIGN KEY (ID_T) REFERENCES TRABAJADOR (ID_T));

CREATE TABLE CLIENTE
(DNI CHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(20),
CONTRASENIA VARCHAR(20));

CREATE TABLE COMPRA 
(DNI CHAR(9),
ID_P VARCHAR(20),
FECHA_COMPRA DATE,
FOREIGN KEY (DNI) REFERENCES CLIENTE (DNI),
FOREIGN KEY (ID_P) REFERENCES PELICULA (ID_P),
PRIMARY KEY (DNI, ID_P));*/		

INSERT INTO TRABAJADOR vALUES
("ADMIN","ADMIN","Admin",2000,"ADMIN");